require('dotenv').config();
const express=require('express'), cors=require('cors'), helmet=require('helmet'), bcrypt=require('bcryptjs'), jwt=require('jsonwebtoken'), sqlite3=require('sqlite3').verbose(), {nanoid}=require('nanoid'), path=require('path'), crypto=require('crypto'), axios=require('axios');
const app=express(); const PORT=process.env.PORT||3000; const JWT_SECRET=process.env.JWT_SECRET||'dev_secret_change_me';
app.use(helmet({contentSecurityPolicy:false})); app.use(cors()); app.use(express.json({limit:'2mb'})); app.use(express.urlencoded({extended:true})); app.use(express.static(path.join(__dirname,'../public')));
const db=new sqlite3.Database(path.join(__dirname,'gorevpazar.db'));
const run=(q,p=[])=>new Promise((res,rej)=>db.run(q,p,function(e){e?rej(e):res(this)}));
const get=(q,p=[])=>new Promise((res,rej)=>db.get(q,p,(e,r)=>e?rej(e):res(r)));
const all=(q,p=[])=>new Promise((res,rej)=>db.all(q,p,(e,r)=>e?rej(e):res(r)));
function auth(req,res,next){const h=req.headers.authorization||''; const t=h.startsWith('Bearer ')?h.slice(7):''; if(!t)return res.status(401).json({error:'Giriş yapmalısınız.'}); try{req.user=jwt.verify(t,JWT_SECRET); next()}catch(e){res.status(401).json({error:'Oturum süresi doldu, tekrar giriş yapın.'})}}
function admin(req,res,next){if(!req.user?.is_admin)return res.status(403).json({error:'Admin yetkisi gerekli.'}); next()}
const bad=['şiddet','silah','uyuşturucu','taciz','tehdit','dolandır','sahte kimlik','hack','hacking','spam','yasa dışı','yasadışı','porno','cinsel'];
function checkTask(t){const s=[t.title,t.description,t.city,t.category].join(' ').toLowerCase(); return bad.find(w=>s.includes(w));}
async function init(){
 await run(`CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,name TEXT,email TEXT UNIQUE,password_hash TEXT,is_admin INTEGER DEFAULT 0,balance INTEGER DEFAULT 0,created_at TEXT DEFAULT CURRENT_TIMESTAMP)`);
 await run(`CREATE TABLE IF NOT EXISTS tasks(id TEXT PRIMARY KEY,owner_id TEXT,title TEXT,category TEXT,city TEXT,budget INTEGER,duration TEXT,description TEXT,status TEXT DEFAULT 'draft',assigned_to TEXT,payment_status TEXT DEFAULT 'unpaid',created_at TEXT DEFAULT CURRENT_TIMESTAMP)`);
 await run(`CREATE TABLE IF NOT EXISTS applications(id TEXT PRIMARY KEY,task_id TEXT,user_id TEXT,message TEXT,status TEXT DEFAULT 'pending',created_at TEXT DEFAULT CURRENT_TIMESTAMP)`);
 await run(`CREATE TABLE IF NOT EXISTS submissions(id TEXT PRIMARY KEY,task_id TEXT,user_id TEXT,note TEXT,proof TEXT,status TEXT DEFAULT 'pending',created_at TEXT DEFAULT CURRENT_TIMESTAMP)`);
 await run(`CREATE TABLE IF NOT EXISTS payments(id TEXT PRIMARY KEY,task_id TEXT,user_id TEXT,amount INTEGER,status TEXT DEFAULT 'pending',provider TEXT DEFAULT 'demo',created_at TEXT DEFAULT CURRENT_TIMESTAMP)`);
 const a=await get('SELECT id FROM users WHERE email=?',['admin@gorevpazar.com']); if(!a) await run('INSERT INTO users VALUES(?,?,?,?,?,?,CURRENT_TIMESTAMP)',['u_admin','GörevPazar Admin','admin@gorevpazar.com',bcrypt.hashSync('admin123',10),1,0]);
 const count=await get('SELECT COUNT(*) c FROM tasks'); if(count.c===0){const owner='u_admin'; const samples=[['Elazığ merkezde mağaza vitrini fotoğrafı çekilecek','Fotoğraf & Video','Elazığ',250,'2 saat','Konuma gidip 5 net fotoğraf çekilecek. Teslim sonrası ödeme serbest bırakılır.'],['Instagram gönderime gerçek kullanıcı yorumu yap','Sosyal Medya','Online',150,'1 gün','Marka kurallarına uygun, spam olmayan doğal yorum yapılacak.'],['Ürün araştırması ve fiyat karşılaştırması yapılacak','Araştırma','Online',300,'3 saat','3 farklı siteden fiyat karşılaştırması ve kısa rapor isteniyor.']]; for(const x of samples) await run('INSERT INTO tasks(id,owner_id,title,category,city,budget,duration,description,status,payment_status) VALUES(?,?,?,?,?,?,?,?,?,?)',[nanoid(),owner,...x,'open','funded']);}
}
app.post('/api/register',async(req,res)=>{try{let {name,email,password}=req.body; email=(email||'').trim().toLowerCase(); if(!name||!email||!password)return res.status(400).json({error:'Ad, e-posta ve şifre zorunlu.'}); if(password.length<6)return res.status(400).json({error:'Şifre en az 6 karakter olmalı.'}); const ex=await get('SELECT id FROM users WHERE email=?',[email]); if(ex)return res.status(409).json({error:'Bu e-posta zaten kayıtlı.'}); const id=nanoid(); await run('INSERT INTO users(id,name,email,password_hash) VALUES(?,?,?,?)',[id,name,email,bcrypt.hashSync(password,10)]); const user={id,name,email,is_admin:0}; res.json({token:jwt.sign(user,JWT_SECRET,{expiresIn:'7d'}),user})}catch(e){res.status(500).json({error:'Kayıt sırasında hata oluştu.'})}});
app.post('/api/login',async(req,res)=>{try{let {email,password}=req.body; email=(email||'').trim().toLowerCase(); const u=await get('SELECT * FROM users WHERE email=?',[email]); if(!u)return res.status(404).json({error:'Bu e-posta kayıtlı değil. Önce kayıt olun.'}); if(!bcrypt.compareSync(password||'',u.password_hash))return res.status(401).json({error:'Şifre hatalı.'}); const user={id:u.id,name:u.name,email:u.email,is_admin:u.is_admin}; res.json({token:jwt.sign(user,JWT_SECRET,{expiresIn:'7d'}),user})}catch(e){res.status(500).json({error:'Giriş sırasında hata oluştu.'})}});
app.get('/api/me',auth,async(req,res)=>{const u=await get('SELECT id,name,email,is_admin,balance FROM users WHERE id=?',[req.user.id]); res.json(u)});
app.get('/api/tasks',async(req,res)=>{const {q='',category='',city=''}=req.query; const rows=await all(`SELECT t.*, u.name owner_name, (SELECT COUNT(*) FROM applications a WHERE a.task_id=t.id) app_count FROM tasks t LEFT JOIN users u ON u.id=t.owner_id WHERE t.status!='draft' AND (?='' OR t.title LIKE ? OR t.description LIKE ?) AND (?='' OR t.category=?) AND (?='' OR t.city LIKE ?) ORDER BY t.created_at DESC`,[q,`%${q}%`,`%${q}%`,category,category,city,`%${city}%`]); res.json(rows)});
app.get('/api/tasks/:id',async(req,res)=>{const t=await get('SELECT t.*,u.name owner_name FROM tasks t LEFT JOIN users u ON u.id=t.owner_id WHERE t.id=?',[req.params.id]); if(!t)return res.status(404).json({error:'Görev bulunamadı.'}); const apps=await all('SELECT a.*,u.name user_name FROM applications a JOIN users u ON u.id=a.user_id WHERE task_id=?',[t.id]); const subs=await all('SELECT s.*,u.name user_name FROM submissions s JOIN users u ON u.id=s.user_id WHERE task_id=?',[t.id]); res.json({...t,applications:apps,submissions:subs})});
app.post('/api/tasks',auth,async(req,res)=>{try{const b=req.body; const badword=checkTask(b); if(badword)return res.status(400).json({error:`Bu görev yayınlanamaz. Yasaklı içerik algılandı: ${badword}`}); if(!b.title||!b.budget||!b.description)return res.status(400).json({error:'Başlık, bütçe ve açıklama zorunlu.'}); const id=nanoid(); await run('INSERT INTO tasks(id,owner_id,title,category,city,budget,duration,description,status,payment_status) VALUES(?,?,?,?,?,?,?,?,?,?)',[id,req.user.id,b.title,b.category||'Diğer',b.city||'Online',parseInt(b.budget),b.duration||'Belirtilmedi',b.description,'pending_payment','unpaid']); res.json({id,message:'Görev oluşturuldu. Yayın için ödeme adımına geçin.'})}catch(e){res.status(500).json({error:'Görev oluşturulamadı.'})}});
app.post('/api/tasks/:id/apply',auth,async(req,res)=>{const t=await get('SELECT * FROM tasks WHERE id=?',[req.params.id]); if(!t)return res.status(404).json({error:'Görev bulunamadı.'}); if(t.owner_id===req.user.id)return res.status(400).json({error:'Kendi görevine başvuramazsın.'}); if(t.status!=='open')return res.status(400).json({error:'Bu görev şu anda başvuru almıyor.'}); const ex=await get('SELECT id FROM applications WHERE task_id=? AND user_id=?',[t.id,req.user.id]); if(ex)return res.status(409).json({error:'Bu göreve zaten başvurdun.'}); await run('INSERT INTO applications(id,task_id,user_id,message) VALUES(?,?,?,?)',[nanoid(),t.id,req.user.id,req.body.message||'Göreve talibim.']); res.json({message:'Başvurun gönderildi.'})});
app.post('/api/applications/:id/accept',auth,async(req,res)=>{const a=await get('SELECT a.*,t.owner_id FROM applications a JOIN tasks t ON t.id=a.task_id WHERE a.id=?',[req.params.id]); if(!a)return res.status(404).json({error:'Başvuru bulunamadı.'}); if(a.owner_id!==req.user.id)return res.status(403).json({error:'Bu işlem sadece görev sahibi tarafından yapılabilir.'}); await run('UPDATE applications SET status="accepted" WHERE id=?',[a.id]); await run('UPDATE applications SET status="rejected" WHERE task_id=? AND id!=?',[a.task_id,a.id]); await run('UPDATE tasks SET assigned_to=?, status="in_progress" WHERE id=?',[a.user_id,a.task_id]); res.json({message:'Başvuru kabul edildi. Görev devam ediyor.'})});
app.post('/api/tasks/:id/submit',auth,async(req,res)=>{const t=await get('SELECT * FROM tasks WHERE id=?',[req.params.id]); if(!t)return res.status(404).json({error:'Görev bulunamadı.'}); if(t.assigned_to!==req.user.id)return res.status(403).json({error:'Bu görev sana atanmadı.'}); await run('INSERT INTO submissions(id,task_id,user_id,note,proof) VALUES(?,?,?,?,?)',[nanoid(),t.id,req.user.id,req.body.note||'',req.body.proof||'']); await run('UPDATE tasks SET status="submitted" WHERE id=?',[t.id]); res.json({message:'Teslim gönderildi. Görev sahibinin onayı bekleniyor.'})});
app.post('/api/tasks/:id/approve',auth,async(req,res)=>{const t=await get('SELECT * FROM tasks WHERE id=?',[req.params.id]); if(!t)return res.status(404).json({error:'Görev bulunamadı.'}); if(t.owner_id!==req.user.id)return res.status(403).json({error:'Sadece görev sahibi onaylayabilir.'}); if(!t.assigned_to)return res.status(400).json({error:'Atanmış kullanıcı yok.'}); const commission=Math.round(t.budget*0.15), payout=t.budget-commission; await run('UPDATE users SET balance=balance+? WHERE id=?',[payout,t.assigned_to]); await run('UPDATE tasks SET status="completed", payment_status="released" WHERE id=?',[t.id]); res.json({message:`Görev onaylandı. ${payout} TL görev yapana aktarıldı, ${commission} TL komisyon kesildi.`})});
app.post('/api/payments/paytr/create',auth,async(req,res)=>{const {task_id}=req.body; const t=await get('SELECT * FROM tasks WHERE id=? AND owner_id=?',[task_id,req.user.id]); if(!t)return res.status(404).json({error:'Görev bulunamadı.'}); const pid=nanoid(); await run('INSERT INTO payments(id,task_id,user_id,amount,status,provider) VALUES(?,?,?,?,?,?)',[pid,t.id,req.user.id,t.budget,'pending','paytr']); if(!process.env.PAYTR_MERCHANT_ID){await run('UPDATE payments SET status="paid" WHERE id=?',[pid]); await run('UPDATE tasks SET status="open", payment_status="funded" WHERE id=?',[t.id]); return res.json({demo:true,message:'Demo ödeme başarılı. PayTR bilgileri eklenince canlı ödeme açılır.',redirect:'/'});} res.json({message:'PayTR canlı entegrasyon noktası hazır. Merchant bilgilerinizle token üretimi aktif edilecek.',payment_id:pid});});
app.get('/api/dashboard',auth,async(req,res)=>{const owned=await all('SELECT * FROM tasks WHERE owner_id=? ORDER BY created_at DESC',[req.user.id]); const assigned=await all('SELECT * FROM tasks WHERE assigned_to=? ORDER BY created_at DESC',[req.user.id]); const apps=await all('SELECT a.*,t.title,t.budget FROM applications a JOIN tasks t ON t.id=a.task_id WHERE a.user_id=? ORDER BY a.created_at DESC',[req.user.id]); res.json({owned,assigned,apps})});
app.get('/api/admin/stats',auth,admin,async(req,res)=>{res.json({users:(await get('SELECT COUNT(*) c FROM users')).c,tasks:(await get('SELECT COUNT(*) c FROM tasks')).c,payments:(await get('SELECT COUNT(*) c FROM payments')).c,volume:(await get('SELECT COALESCE(SUM(amount),0) c FROM payments WHERE status="paid"')).c})});
app.get('/api/admin/users',auth,admin,async(req,res)=>res.json(await all('SELECT id,name,email,is_admin,balance,created_at FROM users ORDER BY created_at DESC')));
app.get('/api/admin/tasks',auth,admin,async(req,res)=>res.json(await all('SELECT * FROM tasks ORDER BY created_at DESC')));
app.post('/api/admin/tasks/:id/status',auth,admin,async(req,res)=>{await run('UPDATE tasks SET status=? WHERE id=?',[req.body.status,req.params.id]); res.json({message:'Durum güncellendi.'})});
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'../public/index.html')));
init().then(()=>app.listen(PORT,()=>console.log(`GörevPazar Full çalışıyor: http://localhost:${PORT}`)));
